//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountessQuantaControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public Action()
        {
            this.SpeechActions = new HashSet<SpeechAction>();
            this.ScreenActions = new HashSet<ScreenAction>();
            this.ServoActions = new HashSet<ServoAction>();
            this.Options = new HashSet<Option>();
        }
    
        public int ActionID { get; set; }
        public string ActionName { get; set; }
        public bool IsParallel { get; set; }
        public bool TimeOffsetSec { get; set; }
        public int SequenceNo { get; set; }
        public string ParentActionID { get; set; }
        public bool Enabled { get; set; }
        public Nullable<int> ActionGroupTypeID { get; set; }
    
        public virtual ActionGroupType ActionGroupType { get; set; }
        public virtual ICollection<SpeechAction> SpeechActions { get; set; }
        public virtual ICollection<ScreenAction> ScreenActions { get; set; }
        public virtual ICollection<ServoAction> ServoActions { get; set; }
        public virtual ICollection<Option> Options { get; set; }
    }
}
