//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountessQuantaControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionGroupType
    {
        public ActionGroupType()
        {
            this.Actions = new HashSet<Action>();
        }
    
        public int ActionGroupTypeID { get; set; }
        public string ActionGroupName { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
    }
}
