//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountessQuantaControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decision
    {
        public Decision()
        {
            this.Options = new HashSet<Option>();
            this.DecisionLogs = new HashSet<DecisionLog>();
        }
    
        public int DecisionID { get; set; }
        public string DecisionName { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<Option> Options { get; set; }
        public virtual ICollection<DecisionLog> DecisionLogs { get; set; }
    }
}
