//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountessQuantaControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatorType
    {
        public OperatorType()
        {
            this.Operators = new HashSet<Operator>();
        }
    
        public int OperatorTypeID { get; set; }
        public string OperatorTypeName { get; set; }
    
        public virtual ICollection<Operator> Operators { get; set; }
    }
}
