//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountessQuantaControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public Option()
        {
            this.Operators = new HashSet<Operator>();
        }
    
        public int OptionID { get; set; }
        public string OptionName { get; set; }
        public decimal Weight { get; set; }
        public int NextDecisionID { get; set; }
        public Nullable<int> DecisionID { get; set; }
        public Nullable<int> ActionID { get; set; }
    
        public virtual Decision Decision { get; set; }
        public virtual Action Action { get; set; }
        public virtual ICollection<Operator> Operators { get; set; }
    }
}
