//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountessQuantaControl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RobotEntitiesContainer : DbContext
    {
        public RobotEntitiesContainer()
            : base("name=RobotEntitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionGroupType> ActionGroupTypes { get; set; }
        public virtual DbSet<ScreenAction> ScreenActions { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<Servo> Servoes { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<OperatorType> OperatorTypes { get; set; }
        public virtual DbSet<SpeechAction> SpeechActions { get; set; }
        public virtual DbSet<DecisionLog> DecisionLogs { get; set; }
        public virtual DbSet<GestureOperator> GestureOperators { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<ServoAction> ServoActions { get; set; }
        public virtual DbSet<SpeechOperator> SpeechOperators { get; set; }
        public virtual DbSet<Decision> Decisions { get; set; }
        public virtual DbSet<ButtonOperator> ButtonOperators { get; set; }
    }
}
