//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountessQuantaControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeechAction
    {
        public int SpeechActionID { get; set; }
        public string Phrase { get; set; }
        public decimal Weight { get; set; }
        public Nullable<int> ActionID { get; set; }
    
        public virtual Action Action { get; set; }
    }
}
